# Generated by Django 3.1.2 on 2020-12-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_customer',
            name='email',
            field=models.EmailField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
