# Generated by Django 3.1.2 on 2020-12-15 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_auto_20201205_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='cat_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creator_profile',
            name='followers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creator_profile',
            name='following',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='following',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='new_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.DateField()),
                ('Address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=40)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower_id', models.IntegerField()),
                ('followed_id', models.IntegerField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
