# Generated by Django 3.1.2 on 2020-12-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20201215_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='user_id',
        ),
        migrations.AddField(
            model_name='followers',
            name='followed_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='following',
        ),
    ]
